import type { SoundPreset } from "./sounds";

// Original synthesized interpretations: no factory patches or hardware samples.
export const iconicSounds = [
  {
    id: "minimoog-bass",
    name: "Ladder bass",
    category: "Bass",
    description:
      "Inspired by Moog Minimoog. Thick saws, sub weight and a warm growl",
    waveform: "sawtooth",
    cutoff: 620,
    resonance: 1.5,
    drive: 2.8,
    level: 0.1,
    octave: -24,
    recipe: {
      layers: [
        { cents: -7, level: 0.4 },
        { waveform: "square", semitones: -12, level: 0.25 },
      ],
      filterRange: 1500,
      filterDecay: 0.22,
    },
  },
  {
    id: "dx7-ep",
    name: "FM tine piano",
    category: "Keys & bells",
    description:
      "Inspired by Yamaha DX7. Glassy FM tine with a soft electric body",
    waveform: "sine",
    cutoff: 8500,
    resonance: 0.5,
    drive: 1,
    level: 0.16,
    octave: 0,
    recipe: {
      fm: { ratio: 14, index: 0.8, decay: 0.3, sustain: 0.04 },
      layers: [{ waveform: "sine", semitones: 12, level: 0.2 }],
      decay: 1.2,
      sustain: 0.35,
      chorus: true,
    },
  },
  {
    id: "juno-pad",
    name: "Chorus pad",
    category: "Pad",
    description:
      "Inspired by Roland Juno. Silky pulse and saw with wide stereo chorus",
    waveform: "sawtooth",
    cutoff: 2100,
    resonance: 0.7,
    drive: 1.15,
    level: 0.12,
    octave: -12,
    recipe: {
      layers: [
        { waveform: "square", cents: 6, level: 0.4 },
        { waveform: "sine", semitones: -12, level: 0.18 },
      ],
      chorus: true,
      attack: 0.35,
      table: "pwm",
    },
  },
  {
    id: "jupiter-brass",
    name: "Analog brass",
    category: "Chords",
    description:
      "Inspired by Roland Jupiter. Bright analog brass with an opening filter",
    waveform: "sawtooth",
    cutoff: 1300,
    resonance: 1.3,
    drive: 1.6,
    level: 0.09,
    octave: -12,
    recipe: {
      layers: [
        { cents: -9, level: 0.35 },
        { semitones: 4, cents: 5, level: 0.4 },
        { semitones: 7, cents: -4, level: 0.35 },
      ],
      attack: 0.05,
      filterRange: 3400,
      filterDecay: 0.45,
      chorus: true,
    },
  },
  {
    id: "prophet-pad",
    name: "Drifting brass pad",
    category: "Pad",
    description:
      "Inspired by Sequential Prophet. Warm drifting oscillators and soft brass",
    waveform: "sawtooth",
    cutoff: 1700,
    resonance: 0.8,
    drive: 1.4,
    level: 0.11,
    octave: -12,
    recipe: {
      layers: [
        { waveform: "triangle", cents: -12, level: 0.55 },
        { cents: 8, level: 0.35 },
      ],
      vibrato: { rate: 0.3, cents: 5 },
      attack: 0.22,
      filterRange: 1300,
      filterDecay: 1.2,
      chorus: true,
    },
  },
  {
    id: "odyssey-lead",
    name: "Dual oscillator lead",
    category: "Lead",
    description:
      "Inspired by ARP Odyssey. Biting dual oscillator lead with filter motion",
    waveform: "sawtooth",
    cutoff: 2200,
    resonance: 3,
    drive: 2.8,
    level: 0.075,
    octave: 0,
    glide: 0.025,
    recipe: {
      layers: [{ waveform: "square", cents: 11, level: 0.5 }],
      table: "sync",
      filterRange: 1700,
      filterDecay: 0.3,
    },
  },
  {
    id: "minimoog-lead",
    name: "Ladder lead",
    category: "Lead",
    description:
      "Inspired by Moog Minimoog. Smooth, powerful analog lead with glide",
    waveform: "sawtooth",
    cutoff: 2600,
    resonance: 1,
    drive: 2,
    level: 0.11,
    octave: 0,
    glide: 0.05,
    recipe: {
      layers: [{ waveform: "square", cents: -5, level: 0.3 }],
      vibrato: { rate: 5, cents: 8 },
      filterRange: 1200,
      filterDecay: 0.3,
    },
  },
  {
    id: "oberheim-brass",
    name: "Wide analog brass",
    category: "Chords",
    description: "Inspired by Oberheim. Wide, bold saw brass in a major chord",
    waveform: "sawtooth",
    cutoff: 4200,
    resonance: 0.6,
    drive: 1.5,
    level: 0.085,
    octave: -12,
    recipe: {
      layers: [
        { cents: -16, level: 0.35 },
        { semitones: 4, cents: 12, level: 0.4 },
        { semitones: 7, cents: -7, level: 0.4 },
        { semitones: 12, cents: 6, level: 0.25 },
      ],
      chorus: true,
      attack: 0.025,
    },
  },
  {
    id: "sh101-bass",
    name: "Pulse sub bass",
    category: "Bass",
    description:
      "Inspired by Roland SH-101. Punchy pulse, saw and sub oscillator",
    waveform: "square",
    cutoff: 700,
    resonance: 2,
    drive: 1.8,
    level: 0.085,
    octave: -24,
    recipe: {
      layers: [
        { waveform: "sawtooth", level: 0.35 },
        { waveform: "square", semitones: -12, level: 0.2 },
      ],
      filterRange: 1800,
      filterDecay: 0.16,
      decay: 0.3,
      sustain: 0.7,
    },
  },
  {
    id: "hoover",
    name: "Rave stack lead",
    category: "Lead",
    description:
      "Inspired by Roland Alpha Juno Hoover. Abrasive rave stack with sweeping pulse motion",
    waveform: "sawtooth",
    cutoff: 5500,
    resonance: 1.5,
    drive: 2.4,
    level: 0.065,
    octave: -12,
    recipe: {
      layers: [
        { cents: -24, level: 0.35 },
        { cents: 24, level: 0.35 },
        { semitones: 12, cents: -12, level: 0.25 },
        { waveform: "square", semitones: -12, level: 0.2 },
      ],
      table: "pwm",
      chorus: true,
      vibrato: { rate: 0.7, cents: 18 },
    },
  },
  {
    id: "m1-piano",
    name: "House piano",
    category: "Keys & bells",
    description:
      "Inspired by Korg M1. Bright house piano attack and rounded sustain",
    waveform: "custom",
    harmonics: [0, 1, 0.55, 0.32, 0.2, 0.12, 0.08],
    cutoff: 6200,
    resonance: 0.5,
    drive: 1.15,
    level: 0.14,
    octave: 0,
    recipe: {
      layers: [{ waveform: "triangle", semitones: 12, cents: 2, level: 0.15 }],
      decay: 0.65,
      sustain: 0.3,
      filterRange: 2000,
      filterDecay: 0.15,
    },
  },
  {
    id: "m1-organ",
    name: "House organ",
    category: "Keys & bells",
    description:
      "Inspired by Korg M1. Hollow house organ with a percussive overtone",
    waveform: "custom",
    harmonics: [0, 1, 0.8, 0.12, 0.5, 0, 0.08, 0, 0.12],
    cutoff: 6200,
    resonance: 0.5,
    drive: 1.1,
    level: 0.13,
    octave: -12,
    recipe: {
      layers: [{ waveform: "sine", semitones: 19, level: 0.18 }],
      decay: 0.45,
      sustain: 0.7,
      chorus: true,
    },
  },
  {
    id: "orchestra-hit",
    name: "Orchestra hit",
    category: "FX",
    description: "Synthesized orchestral stab with a noisy attack",
    waveform: "sawtooth",
    cutoff: 3200,
    resonance: 0.7,
    drive: 1.5,
    level: 0.075,
    octave: -12,
    recipe: {
      layers: [
        { semitones: 7, cents: -13, level: 0.45 },
        { semitones: 12, cents: 17, level: 0.4 },
        { waveform: "triangle", semitones: -12, level: 0.3 },
      ],
      noise: 0.1,
      decay: 0.35,
      sustain: 0.22,
      pitchDrop: 7,
      filterRange: 2800,
      filterDecay: 0.18,
    },
  },
  {
    id: "ppg-pad",
    name: "Metallic wavetable pad",
    category: "Pad",
    description: "Inspired by PPG Wave. Evolving metallic wavetable harmonics",
    waveform: "sawtooth",
    cutoff: 5800,
    resonance: 0.8,
    drive: 1.2,
    level: 0.1,
    octave: -12,
    recipe: {
      table: "wavetable",
      layers: [{ cents: -8, level: 0.35 }],
      chorus: true,
      attack: 0.35,
    },
  },
  {
    id: "d50-fantasia",
    name: "Shimmer bell pad",
    category: "Pad",
    description:
      "Inspired by Roland D-50 Fantasia. Bell attack over a shimmering digital pad",
    waveform: "sine",
    cutoff: 7500,
    resonance: 0.5,
    drive: 1,
    level: 0.11,
    octave: 0,
    recipe: {
      fm: { ratio: 3.5, index: 2, decay: 0.65, sustain: 0.15 },
      layers: [
        { waveform: "triangle", semitones: -12, cents: -8, level: 0.4 },
        { waveform: "sine", semitones: 7, level: 0.25 },
      ],
      chorus: true,
      attack: 0.09,
      delay: { time: 0.28, feedback: 0.25, wet: 0.15 },
    },
  },
  {
    id: "dx7-bass",
    name: "Knock FM bass",
    category: "Bass",
    description: "Inspired by Yamaha DX7. Sharp FM knock with a solid low body",
    waveform: "sine",
    cutoff: 4800,
    resonance: 0.5,
    drive: 1.5,
    level: 0.15,
    octave: -24,
    recipe: {
      fm: { ratio: 1, index: 4.5, decay: 0.15, sustain: 0.4 },
      decay: 0.25,
      sustain: 0.6,
    },
  },
  {
    id: "fm-bell",
    name: "FM bell",
    category: "Keys & bells",
    description: "Metallic inharmonic bell with a long decay",
    waveform: "sine",
    cutoff: 11000,
    resonance: 0.5,
    drive: 1,
    level: 0.13,
    octave: 0,
    recipe: {
      fm: { ratio: 2.71, index: 3, decay: 1.1, sustain: 0.25 },
      decay: 2,
      sustain: 0.3,
      delay: { time: 0.32, feedback: 0.22, wet: 0.12 },
    },
  },
  {
    id: "supersaw",
    name: "Supersaw",
    category: "Lead",
    description: "Seven detuned saws in a wide trance stack",
    waveform: "sawtooth",
    cutoff: 6800,
    resonance: 0.6,
    drive: 1.25,
    level: 0.085,
    octave: 0,
    recipe: {
      layers: [-32, -19, -7, 7, 19, 32].map((cents) => ({
        cents,
        level: 0.28,
      })),
      chorus: true,
    },
  },
  {
    id: "reese-bass",
    name: "Reese bass",
    category: "Bass",
    description: "Dark detuned saws with beating low end",
    waveform: "sawtooth",
    cutoff: 850,
    resonance: 1.5,
    drive: 3.5,
    level: 0.1,
    octave: -24,
    recipe: {
      layers: [
        { cents: -18, level: 0.55 },
        { cents: 18, level: 0.55 },
      ],
      chorus: true,
    },
  },
  {
    id: "pwm-pad",
    name: "PWM pad",
    category: "Pad",
    description: "Slow pulse-width motion and soft stereo shimmer",
    waveform: "square",
    cutoff: 2600,
    resonance: 0.7,
    drive: 1.2,
    level: 0.11,
    octave: -12,
    recipe: {
      table: "pwm",
      layers: [{ waveform: "triangle", cents: 8, level: 0.35 }],
      chorus: true,
      attack: 0.45,
    },
  },
  {
    id: "sync-lead",
    name: "Sync lead",
    category: "Lead",
    description: "Sweeping sync-style harmonics with a sharp edge",
    waveform: "sawtooth",
    cutoff: 6400,
    resonance: 1.5,
    drive: 2,
    level: 0.085,
    octave: 0,
    recipe: { table: "sync", filterRange: 1000, filterDecay: 0.5 },
  },
  {
    id: "acid-squelch",
    name: "Acid squelch",
    category: "Bass",
    description: "Sharper pulse acid with a biting resonant sweep",
    waveform: "square",
    cutoff: 350,
    resonance: 9,
    drive: 3,
    level: 0.055,
    octave: -24,
    glide: 0.045,
    recipe: { filterRange: 4100, filterDecay: 0.23 },
  },
  {
    id: "g-funk",
    name: "G-funk lead",
    category: "Lead",
    description: "High, whiny saw lead with long portamento",
    waveform: "sawtooth",
    cutoff: 2200,
    resonance: 2.5,
    drive: 1.3,
    level: 0.1,
    octave: 12,
    glide: 0.09,
    recipe: { vibrato: { rate: 5.5, cents: 13 } },
  },
  {
    id: "synthwave-bass",
    name: "Synthwave bass",
    category: "Bass",
    description: "Punchy filtered saw and square low end",
    waveform: "sawtooth",
    cutoff: 650,
    resonance: 1.2,
    drive: 2.1,
    level: 0.1,
    octave: -24,
    recipe: {
      layers: [{ waveform: "square", cents: -6, level: 0.4 }],
      filterRange: 2300,
      filterDecay: 0.14,
      decay: 0.3,
      sustain: 0.6,
    },
  },
  {
    id: "cs80-pad",
    name: "Blooming brass pad",
    category: "Pad",
    description:
      "Inspired by Yamaha CS-80. Mournful layered brass with a slow bloom",
    waveform: "sawtooth",
    cutoff: 1400,
    resonance: 1.2,
    drive: 1.5,
    level: 0.1,
    octave: -12,
    recipe: {
      layers: [
        { waveform: "square", cents: -10, level: 0.35 },
        { waveform: "triangle", semitones: -12, level: 0.25 },
      ],
      vibrato: { rate: 4.3, cents: 9 },
      attack: 0.55,
      chorus: true,
      filterRange: 1300,
      filterDecay: 1.6,
    },
  },
  {
    id: "theremin",
    name: "Theremin lead",
    category: "Lead",
    description: "Floating sine lead with gentle vibrato and glide",
    waveform: "sine",
    cutoff: 6500,
    resonance: 0.5,
    drive: 1,
    level: 0.13,
    octave: 12,
    glide: 0.08,
    recipe: { vibrato: { rate: 5.8, cents: 28 }, attack: 0.06 },
  },
  {
    id: "chip-square",
    name: "Chiptune square",
    category: "Lead",
    description: "Clean, narrow pulse from classic game music",
    waveform: "custom",
    harmonics: [0, 1, 0.7, 0.33, 0, -0.2, -0.23, -0.14],
    cutoff: 9000,
    resonance: 0.5,
    drive: 1,
    level: 0.09,
    octave: 0,
    recipe: {},
  },
  {
    id: "chip-arp",
    name: "Chiptune arpeggio",
    category: "Lead",
    description: "Fast root–third–fifth cycling over your equation",
    waveform: "square",
    cutoff: 7200,
    resonance: 0.5,
    drive: 1,
    level: 0.085,
    octave: 0,
    recipe: { arp: true },
  },
  {
    id: "sid",
    name: "Gritty chip bass / lead",
    category: "Lead",
    description:
      "Inspired by Commodore SID. Gritty pulse-width motion and crunchy filtering",
    waveform: "square",
    cutoff: 1800,
    resonance: 2.5,
    drive: 4,
    level: 0.08,
    octave: -12,
    recipe: {
      table: "sid",
      layers: [{ waveform: "triangle", semitones: -12, level: 0.2 }],
      filterRange: 2100,
      filterDecay: 0.25,
    },
  },
  {
    id: "vocoder",
    name: "Vocoder-style voice",
    category: "FX",
    description: "Robotic choir vowels without a microphone",
    waveform: "sawtooth",
    cutoff: 6200,
    resonance: 0.5,
    drive: 1.1,
    level: 0.16,
    octave: -12,
    recipe: {
      layers: [{ waveform: "square", cents: 6, level: 0.3 }],
      formants: [350, 1250, 2500],
      talking: true,
      chorus: true,
    },
  },
  {
    id: "talkbox",
    name: "Talkbox-style lead",
    category: "Lead",
    description: "Nasal vowel-shaped saw with expressive glide",
    waveform: "sawtooth",
    cutoff: 5500,
    resonance: 0.6,
    drive: 2,
    level: 0.16,
    octave: 0,
    glide: 0.06,
    recipe: {
      formants: [500, 1700, 2700],
      talking: true,
      vibrato: { rate: 4.5, cents: 7 },
    },
  },
  {
    id: "formant",
    name: "Talking formant",
    category: "FX",
    description: "Moving ah–ee–oh vowel resonances",
    waveform: "sawtooth",
    cutoff: 6000,
    resonance: 0.5,
    drive: 1.3,
    level: 0.17,
    octave: -12,
    recipe: { formants: [700, 1100, 2450], talking: true },
  },
  {
    id: "dub-chord",
    name: "Dub techno chord",
    category: "Chords",
    description: "Filtered minor chord with dark echo",
    waveform: "sawtooth",
    cutoff: 1200,
    resonance: 1.7,
    drive: 1.5,
    level: 0.1,
    octave: -12,
    recipe: {
      layers: [
        { semitones: 3, cents: -6, level: 0.45 },
        { semitones: 7, cents: 7, level: 0.4 },
      ],
      decay: 0.5,
      sustain: 0.35,
      filterRange: 2000,
      filterDecay: 0.2,
      delay: { time: 0.375, feedback: 0.45, wet: 0.3 },
    },
  },
  {
    id: "trance-pluck",
    name: "Trance pluck",
    category: "Keys & bells",
    description: "Bright detuned pluck with a sparkling echo",
    waveform: "sawtooth",
    cutoff: 1500,
    resonance: 1,
    drive: 1.2,
    level: 0.11,
    octave: 0,
    recipe: {
      layers: [
        { cents: -9, level: 0.3 },
        { cents: 9, level: 0.3 },
      ],
      decay: 0.28,
      sustain: 0.25,
      filterRange: 5200,
      filterDecay: 0.12,
      delay: { time: 0.25, feedback: 0.3, wet: 0.24 },
    },
  },
  {
    id: "future-bass",
    name: "Future bass chord",
    category: "Chords",
    description: "Wide detuned chord with a breathing pulse",
    waveform: "sawtooth",
    cutoff: 3200,
    resonance: 1,
    drive: 1.7,
    level: 0.085,
    octave: -12,
    recipe: {
      layers: [
        { cents: -18, level: 0.3 },
        { semitones: 3, cents: 14, level: 0.4 },
        { semitones: 7, cents: -9, level: 0.4 },
        { semitones: 10, cents: 7, level: 0.25 },
      ],
      chorus: true,
      tremolo: { rate: 2, depth: 0.7 },
      filterRange: 2400,
      filterDecay: 0.5,
    },
  },
  {
    id: "neuro-bass",
    name: "Neuro bass",
    category: "Bass",
    description: "Distorted FM growl with moving vowel filters",
    waveform: "sine",
    cutoff: 3200,
    resonance: 2,
    drive: 4.5,
    level: 0.1,
    octave: -24,
    recipe: {
      fm: { ratio: 1.5, index: 6, decay: 0.7, sustain: 2 },
      layers: [{ waveform: "sawtooth", cents: -15, level: 0.2 }],
      formants: [250, 900, 1800],
      talking: true,
    },
  },
  {
    id: "808-sub",
    name: "Long sub bass",
    category: "Bass",
    description:
      "Inspired by Roland TR-808. Long low sine with a short pitched knock",
    waveform: "sine",
    cutoff: 950,
    resonance: 0.5,
    drive: 2.5,
    level: 0.17,
    octave: -24,
    glide: 0.03,
    recipe: { pitchDrop: 12, decay: 1.5, sustain: 0.6 },
  },
] as const satisfies readonly SoundPreset[];
